# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# keepassxc connector
config.bind('<Alt-Shift-u>', 'spawn --userscript qute-keepassxc --key milind.b.kamble@gmail.com -s /run/user/1000/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer', mode='insert')
config.bind('pw', 'spawn -u qute-keepassxc --key milind.b.kamble@gmail.com -s /run/user/1000/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer', mode='normal')
config.bind('pc', 'jseval if(window.location.href.indexOf("icici")>=0){document.getElementById("user-id-goahead").dispatchEvent(new Event("click",{"bubbles":true}));}')

# bindings for morningstar reports massaging and dumping of html
# bindings starting with 't' seem to support 3 char prefix.
config.bind('tmm', 'jseval -w main window.location.href = $("#sal_iframe")[0].src') # load only the iframe so that DOM contains html of all tables
config.bind('tmf', '''jseval -w main $("a.mds-link:contains('Details View')")[0].click()''') # expand the details view
config.bind('tma', '''jseval -w main $("mds-button[value='Annual']")[0].click(); $("mds-button[value='Restated']")[0].click()''') # select Annual-restated view of financials
config.bind('tme', '''jseval -w main $.each($("a.more-data"), function(index,val){val.click();})''') # expand all sections
config.bind('tmx', '''jseval -w main $("button.sal-financials-details__export")[0].click()''') # export the financials into excel using Export-to-Excel
config.bind('tmi', '''jseval -w main $("mds-button[value='Income Statement']")[0].click()''') #  income statement
config.bind('tmb', '''jseval -w main $("mds-button[value='Balance Sheet']")[0].click()''') # balance sheet statement
config.bind('tmc', '''jseval -w main $("mds-button[value='Cash Flow']")[0].click()''') # cash flow statement
config.bind('tms', 'jseval --file -w main dump_current_DOM.js', mode='normal') # save html source to extract valuation and oper-perf data

# disable ad block temporarily
config.bind(',a', 'set content.blocking.enabled false ;; reload -f ;; later 5s set content.blocking.enabled true')
