# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# keepassxc connector
config.bind('<Alt-Shift-u>', 'spawn --userscript qute-keepassxc --key milind.b.kamble@gmail.com -s /run/user/1000/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer', mode='insert')
config.bind('pw', 'spawn -u qute-keepassxc --key milind.b.kamble@gmail.com -s /run/user/1000/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer', mode='normal')
config.bind('pc', 'jseval if(window.location.href.indexOf("icici")>=0){document.getElementById("user-id-goahead").dispatchEvent(new Event("click",{"bubbles":true}));}')

# bindings for morningstar reports massaging and dumping of html
config.bind('pm', 'jseval --file -w main mrgstar_load_sal_iframe.js', mode='normal')
config.bind('tmi', 'jseval --file -w main mrgstar_financials_income.js', mode='normal')
config.bind('tmc', 'jseval --file -w main mrgstar_financials_cash.js', mode='normal')
config.bind('tmb', 'jseval --file -w main mrgstar_financials_balance.js', mode='normal')
config.bind('tmx', 'jseval --file -w main mrgstar_expand_sections.js', mode='normal')
config.bind('tme', 'jseval --file -w main mrgstar_financials_export.js', mode='normal')
config.bind('ps', 'jseval --file -w main dump_current_DOM.js', mode='normal')

# disable ad block temporarily
config.bind(',a', 'set content.blocking.enabled false ;; reload -f ;; later 5s set content.blocking.enabled true')
